### ISSUE TITLE
OpenAI autologin via playwright

### ISSUE THREAD

**Issue by sebaplaza** [altryne/chatGPT-telegram-bot#19]
Hello,

I'm currently creating a [Docker image](https://github.com/altryne/chatGPT-telegram-bot/pull/18) to chatGPT-telegram-bot.

Like we need to use the headless playwright mode, we also need to integrate OpenAI autologin in playwright via environment variables.

**Comment by ahmedRSA** [comment]
> We must code the login interaction using playwright to pass OpenAI user/password.
> 
> Then, we could set environment variables like
> 
> OPENAI_USER OPENAI_PASSWORD

r u working on automating login? 
i tried but failed

**Comment by sebaplaza** [comment]
no, i'm not a python developer.

i could try, but i was waiting for an answer from @altryne

**Comment by altryne** [comment]
I don't know why I'm not getting notifications for these! 
Thanks @sebaplaza 
I'm taking a look at the PR
