### ISSUE TITLE
No Module named Telegram?

### ISSUE THREAD

**Issue by Maki9009** [altryne/chatGPT-telegram-bot#3]
not sure what i did wrong but im getting a no telegram error, this is after installing everything and trying to run the server.

**Comment by samching** [comment]
You have to create an environment as directed in the Readme: https://github.com/altryne/chatGPT-telegram-bot/blob/main/environment.yml

The python package in question is `python-telegram-bot`

**Comment by Maki9009** [comment]
i did create the environment though

**Comment by altryne** [comment]
fixed in #4
