### ISSUE TITLE
Headless mode does not work

### ISSUE THREAD

**Issue by mrben1** [altryne/chatGPT-telegram-bot#34]
Headless mode does not seem to be working for me, it times out when trying to find the password field... is this due to RECaptcha?

chatgpt-telegram-bot  | Please log in to OpenAI Chat
chatgpt-telegram-bot`  | Press enter when you're done
chatgpt-telegram-bot  | Traceback (most recent call last):
chatgpt-telegram-bot  |   File "/app/server.py", line 307, in <module>
chatgpt-telegram-bot  |     start_browser()
chatgpt-telegram-bot  |   File "/app/server.py", line 275, in start_browser
chatgpt-telegram-bot  |     username.fill(OPEN_AI_EMAIL)
chatgpt-telegram-bot  |   File "/home/pwuser/.local/lib/python3.10/site-packages/playwright/sync_api/_generated.py", line 13978, in fill
chatgpt-telegram-bot  |     self._sync(
chatgpt-telegram-bot  |   File "/home/pwuser/.local/lib/python3.10/site-packages/playwright/_impl/_sync_base.py", line 104, in _sync
chatgpt-telegram-bot  |     return task.result()
chatgpt-telegram-bot  |   File "/usr/lib/python3.10/asyncio/futures.py", line 201, in result
chatgpt-telegram-bot  |     raise self._exception.with_traceback(self._exception_tb)
chatgpt-telegram-bot  |   File "/usr/lib/python3.10/asyncio/tasks.py", line 232, in __step
chatgpt-telegram-bot  |     result = coro.send(None)
chatgpt-telegram-bot  |   File "/home/pwuser/.local/lib/python3.10/site-packages/playwright/_impl/_locator.py", line 198, in fill
chatgpt-telegram-bot  |     return await self._frame.fill(self._selector, strict=True, **params)
chatgpt-telegram-bot  |   File "/home/pwuser/.local/lib/python3.10/site-packages/playwright/_impl/_frame.py", line 528, in fill
chatgpt-telegram-bot  |     await self._channel.send("fill", locals_to_params(locals()))
chatgpt-telegram-bot  |   File "/home/pwuser/.local/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 44, in send
chatgpt-telegram-bot  |     return await self._connection.wrap_api_call(
chatgpt-telegram-bot  |   File "/home/pwuser/.local/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 419, in wrap_api_call
chatgpt-telegram-bot  |     return await cb()
chatgpt-telegram-bot  |   File "/home/pwuser/.local/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 79, in inner_send
chatgpt-telegram-bot  |     result = next(iter(done)).result()
chatgpt-telegram-bot  |   File "/usr/lib/python3.10/asyncio/futures.py", line 201, in result
chatgpt-telegram-bot  |     raise self._exception.with_traceback(self._exception_tb)
chatgpt-telegram-bot  | playwright._impl._api_types.TimeoutError: Timeout 30000ms exceeded.
chatgpt-telegram-bot  | =========================== logs ===========================
chatgpt-telegram-bot  | waiting for locator("input[name=\"username\"]")
chatgpt-telegram-bot  | ============================================================
chatgpt-telegram-bot exited with code 1

**Comment by altryne** [comment]
Try without headless to login and then switch to headless
